version: '3.9'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_proxy
    restart: unless-stopped
    networks:
      - nginx-proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - './volumes/config/:/etc/nginx'
      # - './volumes/config/nginx.conf:/etc/nginx/nginx.conf'
      # - './volumes/config/conf.d/:/etc/nginx/conf.d/'
      # - './volumes/logs/error_log:/etc/nginx/error_log.log'
      # - './volumes/cache/:/etc/nginx/cache'

networks:
  nginx-proxy:
    external: true
